# Generated by Django 3.2 on 2021-02-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal_app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arubaito',
            name='days',
        ),
        migrations.RemoveField(
            model_name='arubaito',
            name='time',
        ),
    ]
