# Generated by Django 3.2 on 2021-02-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal_app1', '0002_auto_20210206_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='arubaito_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Days', models.CharField(max_length=255)),
                ('Times', models.CharField(max_length=255)),
                ('day_time', models.CharField(max_length=255, unique=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal_app1.arubaito_name')),
            ],
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Arubaito',
        ),
        migrations.DeleteModel(
            name='Working_Time',
        ),
        migrations.RemoveField(
            model_name='day',
            name='name',
        ),
        migrations.AddField(
            model_name='day',
            name='day',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
